name: my_new_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # âœ… Firebase dependencies
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  firebase_messaging: ^14.9.0
  cloud_firestore: ^4.14.0
  image_picker: ^1.1.2
  firebase_storage: ^11.2.7
  url_launcher: ^6.2.5
  intl: ^0.19.0
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboard.jpg
    - assets/images/plumbing.jpg
    - assets/images/electrician.jpg
    - assets/images/cleaning.jpg
    - assets/images/painter.jpg
    - assets/images/sale_banner_bg.jpg
    - assets/images/carpenter.jpg
    - assets/images/plumber_provider.jpg
    - assets/images/electrician_provider.jpg
    - assets/images/Ali_painter.jpg
    - assets/images/Carpenter_provider.jpeg
    - assets/images/cleaning_provider.jpg
    - assets/images/Construction.jpg
    - assets/images/Architects.jpg
    - assets/images/Interior.jpg
    - assets/images/Furniture.jpg
    - assets/images/tiling.jpg
    - assets/images/Construction_provider.jpg
    - assets/images/Architects_provider.jpg
    - assets/images/Daniels_Design.jpg
    - assets/images/Furniture_provider.jpg
    - assets/images/tiler_provider.jpg
    - assets/images/Home.jpg
    - assets/images/Home1.jpg
    - assets/images/Home2.jpg
    - assets/images/HomeInteriors.jpg
    - assets/images/ModularKitchen.jpg
    - assets/images/paytm_logo.jpg
    - assets/images/phonepe_logo.jpg
    - assets/images/amazonpay_logo.jpg
    - assets/images/freecharge_logo.jpg
    - assets/images/olamoney_logo.jpg
    - assets/images/Interior.jpg
    - assets/images/sofa_cleaning.jpg
    - assets/images/kitchen_cleaning.jpg
    - assets/images/bathroom_cleaning.jpg
    - assets/images/carpet_cleaning.jpg
    - assets/images/pipe.jpg
    - assets/images/WaterHeaterInstall.jpg
    - assets/images/DrainCleaning.jpg
    - assets/images/WiringFix.jpg
    - assets/images/ApplianceInstallation.jpg
    - assets/images/FurnitureRepair.jpg
    - assets/images/InteriorPainting.jpg
    - assets/images/ExteriorPainting.jpg
    - assets/images/DoorRepair.jpg
    - assets/images/CommercialBuilding.jpg
    - assets/images/OfficeInterior.jpg
    - assets/images/bedroom_header.jpg
    - assets/images/ACService.jpg
    - assets/images/ElectricalFaultRepair.jpg
    - assets/images/PestControl.jpg
    - assets/images/FullHouseCleaning.jpg
    - assets/images/discount.jpg



  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
